### ISSUE TITLE
Padding on Outlook/Windows Mail

### ISSUE THREAD

**Issue by lucaball** [antibodies-online/bootstrap-email#3]
Hi!

First of all, thank you for the package!

But I do notice some weird behaviour regarding padding for elements in Windows Mail / Outlook. It looks like they are not applied at all. 

If I convert my HTML with the online editor from Bootstrap Email Editor, and mail it to that inbox, it looks okay, but if I use the package, the padding is missing. 

Output in the online editor: 
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/57355230/173079012-d30bce0d-e630-46c4-9c93-e187b0296ab2.png">

Output in the mailclient when using the package
<img width="641" alt="image" src="https://user-images.githubusercontent.com/57355230/173079621-fd634b21-6417-484d-bff5-431397939352.png">

Is this something you are aware of? 

Thanks in advance!

Kind regards!

**Comment by DemigodCode** [comment]
Hey Lucas,

I'm aware of that weird bug but didn't find the issue yet.

As we the package is using the same .scss, there's maybe something with the compiler package for scss. But I did not dig deeper into it, as of now.

If you would try to locate the difference between the original bootstrap-email css output and this package, that would be great!

**Comment by lucaball** [comment]
I will give it a try! I'll keep you posted!

**Comment by lucaball** [comment]
I don't know if you're anything with this? Left is generated with the package, right with online Bootstrap Email Editor. 

https://www.diffchecker.com/HwrcjOzB

**Comment by DemigodCode** [comment]
The diff can't be completly without any diff. The packages for inline css in php and ruby, are sorting values not the same way.

So you have to compare the rendering and dig into it, if a css-class/inline style not isset, which is set in the ruby original package.

**Comment by DemigodCode** [comment]
So, at least the scss '.btn" rule adds this:

`border: $btn-border-width solid transparent;`

Then, with a "btn-$color" rule, the border-color will be set on the element.
In Ruby, the original border attribute will be modified as follows:

`border: $btn-border-width solid $color;`

The PHP, i guess it should be the task of the css inliner, there's nothing merged into the border attribute. It just adds the border-color attribute and that is not processed by outlook.

I will add a new line in the scss files, which should work as workaround. But we should open an issue in the css inliner.

**Comment by DemigodCode** [comment]
Fixed as of now in v1.0.2
