### ISSUE TITLE
Missing responsive CSS columns

### ISSUE THREAD

**Issue by fonnets** [antibodies-online/bootstrap-email#4]
Hi Benedikt, first of all I would like to congratulate you on the php port, magnificent work. This library was great in ruby but having it in php makes it much more usable!

I noticed that compared to the online editor the css of the media screen columns is not created:

```
        .
        .
        .
        table:not([class^=s-]) td {
            border-spacing: 0px;
            border-collapse: collapse;
        }

        \n

        @media screen and (max-width: 600px) {
            \n *[class*=s-lg-] > tbody > tr > td {
                font-size: 0 !important;
                line-height: 0 !important;
                height: 0 !important;
            }

            \n
        }
```

(I think the printing of '\n' is another small bug that needs fixing.)

While in the bootstrap-email online editor the column classes are created:

```
         @media screen and (max-width: 600px) {
            .row-responsive.row {
                margin-right: 0 !important
            }

            td.col-lg-3 {
                display: block;
                width: 100% !important;
                padding-left: 0 !important;
                padding-right: 0 !important
            }
            
           .
           .
           .
        }
```

I would also like to point out that to convert the code I used the `compileHtml` method and not `convertHtml` as reported in the usage documentation because this method does not exist.

Thank you!

**Comment by DemigodCode** [comment]
https://github.com/antibodies-online/bootstrap-email/pull/5
