### ISSUE TITLE
Images proportions [nested tables]

### ISSUE THREAD

**Issue by fonnets** [antibodies-online/bootstrap-email#6]
Hi, I would like to point out that there are some problems with the aspect ratio of the images.
Using this bootstrap code in the bootstrapemail online editor the aspect ratio are respected:

```
<body>
<div class="container my-4">
    <div class="row my-3 pb-2">
        <div class="col-lg-3 bg-warning">
            <img class="img-fluid ax-center max-h-48 p-1" src="https://placehold.co/300x300/jpg">
        </div>
        <div class="col-lg-5 bg-danger">
            col-5
        </div>
        <div class="col-lg-4 bg-success">
            col-4
        </div>
    </div>
    <div class="row my-3 pb-2">
        <div class="col-lg-3 bg-warning">
            <img class="img-fluid ax-center max-h-48 p-1" src="https://placehold.co/300x100/jpg">
        </div>
        <div class="col-lg-5 bg-danger">
            col-5
        </div>
        <div class="col-lg-4 bg-success">
            col-4
        </div>
    </div>
    <div class="row my-3 pb-2">
        <div class="col-lg-3 bg-warning">
            <img class="img-fluid ax-center max-h-48 p-1" src="https://placehold.co/100x300/jpg">
        </div>
        <div class="col-lg-5 bg-danger">
            col-5
        </div>
        <div class="col-lg-4 bg-success">
            col-4
        </div>
    </div>
</div>
</body>
```

<img width="658" alt="bootstrapemail-ruby-desktop" src="https://github.com/antibodies-online/bootstrap-email/assets/90871496/e1bbef80-4d02-4da1-8095-a14bb781d3a5">
<img width="320" alt="bootstrapemail-ruby-mobile" src="https://github.com/antibodies-online/bootstrap-email/assets/90871496/1b8cccd7-234d-4535-8cc9-051a679d7fac">

While in php I get this result:

<img width="662" alt="bootstrapemail-php-desktop" src="https://github.com/antibodies-online/bootstrap-email/assets/90871496/000a9fad-f42d-4d88-a6da-9e3e16fd989a">
<img width="316" alt="bootstrapemail-php-mobile" src="https://github.com/antibodies-online/bootstrap-email/assets/90871496/e1cb6acb-75c9-4878-bd32-9eb5f5d1bdc1">

It seems the reason is due to a lack of a table. In ruby ​​bootstrapemail the img tag is wrapped in 2 nested tables, one for the 'ax-center' class and one for the 'p-1' class, while in php it wraps only with 'ax-center' and not for 'p- 1'.

I tried for a whole day to understand how to solve it but at the moment I couldn't...

Thank you

**Comment by fonnets** [comment]
I don't think a new template is needed because the already existing `table.html` can be used.
Copying the `buildReplacementHtml` method of the `Align` class into the `Padding` class also seems to nest the second table relating to 'p-1' correctly:

```
    public function buildReplacementHtml(\DOMElement $element, string $identifier): string
    {
        if ($element->tagName !== 'table' && $element->tagName !== 'td') {
            return parent::buildReplacementHtml($element, $identifier);
        }
        return $element->ownerDocument->saveHTML($element);
    }
```

However, this is not enough to make the images proportionate because all the classes of the `img` tag are still copied into each table. We need to find a way to obtain the same result as the online editor that creates a table with only the `ax-center` class and one with only the `p-1` class. 
I think the problem lies in the class removals.
For example, I notice that on the `Padding` class in the `extractParentCssClasses` method there is a `preg_match_all` but then the result is not used, is this intentional?

```
    protected function extractParentCssClasses(\DOMElement $element, string $identifier): string
    {
        $classes = [];
        preg_match_all($this->paddingRegex, parent::extractParentCssClasses($element, $identifier), $classes);
        return parent::extractParentCssClasses($element, $identifier) . ' w-full';
    }
```

**Comment by fonnets** [comment]
#7

**Comment by ebazot** [comment]
Thank you very much!
